<?php
 
$_SESSION["REFERENCE"] = $_RESPONSE['REFERENCE'];
$_SESSION["STATUS"] = $_RESPONSE['STATUS'];
$_SESSION["DESTINATION"] = $_RESPONSE['DESTINATION'];
$_SESSION["REASON"] = $_RESPONSE['REASON'];
$_SESSION["TIMESTAMP"] = $_RESPONSE['TIMESTAMP'];
$_SESSION["OPERATOR"] = $_RESPONSE['OPERATOR'];

echo "OK";
header('Location: showDeliveryStatus.php');
?>